/**
 * Idiomas para "idioma original" do projeto de dublagem.
 * `value`: preferencialmente ISO 639-1 (2 letras); gravado em DubbingProject.language.
 * `search`: termos extras para filtro (inglês, nativo, abreviações).
 */

export type OriginalLanguage = {
  value: string;
  label: string;
  /** Texto extra para pesquisa (minúsculas, sem acento obrigatório — o filtro normaliza) */
  search: string;
};

/** Lista extensa (maioria dos ISO 639-1 usuais + variantes comuns). */
export const ORIGINAL_LANGUAGES: OriginalLanguage[] = [
  { value: "aa", label: "Afar", search: "afar afar af" },
  { value: "ab", label: "Abkhaziano", search: "abkhazian abkhaz" },
  { value: "ae", label: "Avéstico", search: "avestan" },
  { value: "af", label: "Africâner", search: "afrikaans south africa" },
  { value: "ak", label: "Akan", search: "akan ghana" },
  { value: "am", label: "Amárico", search: "amharic ethiopia etiópia" },
  { value: "an", label: "Aragonês", search: "aragonese" },
  { value: "ar", label: "Árabe", search: "arabic العربية" },
  { value: "as", label: "Assamês", search: "assamese india" },
  { value: "av", label: "Avar", search: "avar" },
  { value: "ay", label: "Aimará", search: "aymara aymara" },
  { value: "az", label: "Azerbaijano", search: "azerbaijani azeri" },
  { value: "ba", label: "Basquir", search: "bashkir" },
  { value: "be", label: "Bielorrusso", search: "belarusian belarus" },
  { value: "bg", label: "Búlgaro", search: "bulgarian bulgaria" },
  { value: "bh", label: "Bihari", search: "bihari" },
  { value: "bi", label: "Bislamá", search: "bislama vanuatu" },
  { value: "bm", label: "Bambara", search: "bambara mali" },
  { value: "bn", label: "Bengali", search: "bangla bengali bangladesh india" },
  { value: "bo", label: "Tibetano", search: "tibetan" },
  { value: "br", label: "Bretão", search: "breton brittany" },
  { value: "bs", label: "Bósnio", search: "bosnian bosnia" },
  { value: "ca", label: "Catalão", search: "catalan catalonia" },
  { value: "ce", label: "Checheno", search: "chechen" },
  { value: "ch", label: "Chamorro", search: "chamorro guam" },
  { value: "co", label: "Corso", search: "corsican corsica" },
  { value: "cr", label: "Cree", search: "cree" },
  { value: "cs", label: "Tcheco", search: "czech czechia čeština" },
  { value: "cu", label: "Eslavo eclesiástico", search: "church slavic" },
  { value: "cv", label: "Tchuvache", search: "chuvash" },
  { value: "cy", label: "Galês", search: "welsh wales cymraeg" },
  { value: "da", label: "Dinamarquês", search: "danish denmark dansk" },
  { value: "de", label: "Alemão", search: "german deutsch germany" },
  { value: "dv", label: "Diveí", search: "dhivehi maldivian maldives" },
  { value: "dz", label: "Dzonga", search: "dzongkha bhutan" },
  { value: "ee", label: "Ewe", search: "ewe togo ghana" },
  { value: "el", label: "Grego", search: "greek greece ελληνικά" },
  { value: "en", label: "Inglês", search: "english" },
  { value: "eo", label: "Esperanto", search: "esperanto" },
  { value: "es", label: "Espanhol", search: "spanish español castellano" },
  { value: "et", label: "Estoniano", search: "estonian estonia eesti" },
  { value: "eu", label: "Basco", search: "basque euskera" },
  { value: "fa", label: "Persa (farsi)", search: "persian farsi iran فارسی" },
  { value: "ff", label: "Fula", search: "fulah fulani peul" },
  { value: "fi", label: "Finlandês", search: "finnish finland suomi" },
  { value: "fj", label: "Fijiano", search: "fijian fiji" },
  { value: "fo", label: "Faroês", search: "faroese faroe" },
  { value: "fr", label: "Francês", search: "french français france" },
  { value: "fy", label: "Frísio ocidental", search: "western frisian frisian" },
  { value: "ga", label: "Irlandês", search: "irish gaelic ireland gaeilge" },
  { value: "gd", label: "Gaélico escocês", search: "scottish gaelic scotland" },
  { value: "gl", label: "Galego", search: "galician galiza" },
  { value: "gn", label: "Guarani", search: "guarani paraguay" },
  { value: "gu", label: "Guzerate", search: "gujarati india" },
  { value: "gv", label: "Manx", search: "manx isle of man" },
  { value: "ha", label: "Hauçá", search: "hausa nigeria" },
  { value: "he", label: "Hebraico", search: "hebrew israel עברית" },
  { value: "hi", label: "Hindi", search: "hindu india हिन्दी" },
  { value: "ho", label: "Hiri motu", search: "hiri motu png" },
  { value: "hr", label: "Croata", search: "croatian croatia hrvatski" },
  { value: "ht", label: "Haitiano", search: "haitian creole haiti" },
  { value: "hu", label: "Húngaro", search: "hungarian hungary magyar" },
  { value: "hy", label: "Armênio", search: "armenian armenia հայերեն" },
  { value: "hz", label: "Hereró", search: "herero" },
  { value: "ia", label: "Interlíngua", search: "interlingua" },
  { value: "id", label: "Indonésio", search: "indonesian indonesia bahasa" },
  { value: "ie", label: "Interlingue", search: "interlingue occidental" },
  { value: "ig", label: "Igbo", search: "igbo nigeria" },
  { value: "ii", label: "Nuosu (Yi)", search: "sichuan yi nuosu" },
  { value: "ik", label: "Inupiaq", search: "inupiaq inuit" },
  { value: "io", label: "Ido", search: "ido" },
  { value: "is", label: "Islandês", search: "icelandic iceland íslenska" },
  { value: "it", label: "Italiano", search: "italian italy italiano" },
  { value: "iu", label: "Inuktitut", search: "inuktitut inuit" },
  { value: "ja", label: "Japonês", search: "japanese japan 日本語 nippon" },
  { value: "jv", label: "Javanês", search: "javanese java indonesia" },
  { value: "ka", label: "Georgiano", search: "georgian georgia ქართული" },
  { value: "kg", label: "Kongo", search: "kongo congo" },
  { value: "ki", label: "Quicuio", search: "kikuyu kenya" },
  { value: "kj", label: "Cuanhama", search: "kuanyama" },
  { value: "kk", label: "Cazaque", search: "kazakh kazakhstan" },
  { value: "kl", label: "Groenlandês", search: "greenlandic kalaallisut" },
  { value: "km", label: "Khmer (cambojano)", search: "khmer cambodian cambodia" },
  { value: "kn", label: "Canarês", search: "kannada india" },
  { value: "ko", label: "Coreano", search: "korean korea 한국어" },
  { value: "kr", label: "Canúri", search: "kanuri" },
  { value: "ks", label: "Caxemira", search: "kashmiri" },
  { value: "ku", label: "Curdo", search: "kurdish kurd" },
  { value: "kv", label: "Komi", search: "komi" },
  { value: "kw", label: "Córnico", search: "cornish cornwall" },
  { value: "ky", label: "Quirguiz", search: "kyrgyz kirghiz" },
  { value: "la", label: "Latim", search: "latin" },
  { value: "lb", label: "Luxemburguês", search: "luxembourgish luxembourg" },
  { value: "lg", label: "Luganda", search: "ganda luganda uganda" },
  { value: "li", label: "Limburguês", search: "limburgish" },
  { value: "ln", label: "Lingala", search: "lingala congo" },
  { value: "lo", label: "Lao", search: "lao laotian laos" },
  { value: "lt", label: "Lituano", search: "lithuanian lithuania lietuvių" },
  { value: "lu", label: "Luba-catanga", search: "luba-katanga" },
  { value: "lv", label: "Letão", search: "latvian latvia latviešu" },
  { value: "mg", label: "Malgaxe", search: "malagasy madagascar" },
  { value: "mh", label: "Marshalês", search: "marshallese" },
  { value: "mi", label: "Maori", search: "maori māori new zealand" },
  { value: "mk", label: "Macedônio", search: "macedonian north macedonia" },
  { value: "ml", label: "Malaiala", search: "malayalam india" },
  { value: "mn", label: "Mongol", search: "mongolian mongolia" },
  { value: "mr", label: "Marata", search: "marathi india" },
  { value: "ms", label: "Malaio", search: "malay malaysia bahasa melayu" },
  { value: "mt", label: "Maltês", search: "maltese malta" },
  { value: "my", label: "Birmanês", search: "burmese myanmar မြန်မာ" },
  { value: "na", label: "Nauruano", search: "nauru" },
  { value: "nb", label: "Norueguês (bokmål)", search: "norwegian bokmal norway norsk" },
  { value: "nd", label: "Ndebele do norte", search: "north ndebele zimbabwe" },
  { value: "ne", label: "Nepalês", search: "nepali nepal" },
  { value: "ng", label: "Ndonga", search: "ndonga namibia" },
  { value: "nl", label: "Holandês / neerlandês", search: "dutch netherlands nederlands holanda" },
  { value: "nn", label: "Norueguês (nynorsk)", search: "norwegian nynorsk" },
  { value: "no", label: "Norueguês", search: "norwegian norway norsk" },
  { value: "nr", label: "Ndebele do sul", search: "south ndebele" },
  { value: "nv", label: "Navajo", search: "navajo diné" },
  { value: "ny", label: "Nianja (Chichewa)", search: "chichewa chewa nyanja malawi" },
  { value: "oc", label: "Occitano", search: "occitan occitanie" },
  { value: "oj", label: "Ojíbua", search: "ojibwe ojibwa" },
  { value: "om", label: "Oromo", search: "oromo ethiopia" },
  { value: "or", label: "Oriá", search: "odia oriya india" },
  { value: "os", label: "Osseto", search: "ossetian ossetia" },
  { value: "pa", label: "Punjabi", search: "punjabi panjabi india pakistan" },
  { value: "pi", label: "Páli", search: "pali" },
  { value: "pl", label: "Polonês", search: "polish poland polski" },
  { value: "ps", label: "Pashto", search: "pashto pushto afghanistan" },
  { value: "pt", label: "Português", search: "portuguese portugal brasil brazil" },
  { value: "qu", label: "Quíchua", search: "quechua runasimi" },
  { value: "rm", label: "Romanche", search: "romansh switzerland" },
  { value: "rn", label: "Kirundi", search: "rundi burundi" },
  { value: "ro", label: "Romeno", search: "romanian romania română" },
  { value: "ru", label: "Russo", search: "russian russia русский" },
  { value: "rw", label: "Quiniaruanda", search: "kinyarwanda rwanda" },
  { value: "sa", label: "Sânscrito", search: "sanskrit" },
  { value: "sc", label: "Sardo", search: "sardinian sardinia" },
  { value: "sd", label: "Sindi", search: "sindhi pakistan india" },
  { value: "se", label: "Sami do norte", search: "northern sami sámi" },
  { value: "sg", label: "Sango", search: "sango car" },
  { value: "si", label: "Cingalês", search: "sinhala sinhalese sri lanka" },
  { value: "sk", label: "Eslovaco", search: "slovak slovakia slovenčina" },
  { value: "sl", label: "Esloveno", search: "slovenian slovenia slovenščina" },
  { value: "sm", label: "Samoano", search: "samoan samoa" },
  { value: "sn", label: "Xona", search: "shona zimbabwe" },
  { value: "so", label: "Somali", search: "somali somalia" },
  { value: "sq", label: "Albanês", search: "albanian albania shqip" },
  { value: "sr", label: "Sérvio", search: "serbian serbia српски" },
  { value: "ss", label: "Suázi", search: "swati swaziland eswatini" },
  { value: "st", label: "Soto do sul", search: "southern sotho lesotho" },
  { value: "su", label: "Sundanês", search: "sundanese indonesia" },
  { value: "sv", label: "Sueco", search: "swedish sweden svenska" },
  { value: "sw", label: "Suaíli", search: "swahili kiswahili east africa" },
  { value: "ta", label: "Tâmil", search: "tamil india sri lanka" },
  { value: "te", label: "Telugo", search: "telugu india" },
  { value: "tg", label: "Tadjique", search: "tajik tajikistan" },
  { value: "th", label: "Tailandês", search: "thai thailand ไทย" },
  { value: "ti", label: "Tigrínia", search: "tigrinya eritrea ethiopia" },
  { value: "tk", label: "Turcomeno", search: "turkmen turkmenistan" },
  { value: "tl", label: "Tagalo / filipino", search: "tagalog filipino philippines" },
  { value: "tn", label: "Tsuana", search: "tswana botswana" },
  { value: "to", label: "Tonganês", search: "tongan tonga" },
  { value: "tr", label: "Turco", search: "turkish turkey türkçe" },
  { value: "ts", label: "Tsonga", search: "tsonga south africa" },
  { value: "tt", label: "Tártaro", search: "tatar" },
  { value: "tw", label: "Tui", search: "twi akan ghana" },
  { value: "ty", label: "Taitiano", search: "tahitian french polynesia" },
  { value: "ug", label: "Uigure", search: "uyghur uighur" },
  { value: "uk", label: "Ucraniano", search: "ukrainian ukraine українська" },
  { value: "ur", label: "Urdu", search: "urdu pakistan india" },
  { value: "uz", label: "Uzbeque", search: "uzbek uzbekistan" },
  { value: "ve", label: "Venda", search: "venda south africa" },
  { value: "vi", label: "Vietnamita", search: "vietnamese vietnam tiếng việt" },
  { value: "vo", label: "Volapuque", search: "volapük" },
  { value: "wa", label: "Valão", search: "walloon belgium" },
  { value: "wo", label: "Uolofe", search: "wolof senegal" },
  { value: "xh", label: "Xhosa", search: "xhosa south africa" },
  { value: "yi", label: "Iídiche", search: "yiddish" },
  { value: "yo", label: "Iorubá", search: "yoruba nigeria" },
  { value: "za", label: "Zhuang", search: "zhuang china" },
  { value: "zh", label: "Chinês", search: "chinese mandarin cantonese 中文 汉语 china" },
  { value: "zu", label: "Zulu", search: "zulu south africa" },
  { value: "other", label: "Outro / não listado", search: "outro other custom misc vários" },
];

const byValue = new Map(ORIGINAL_LANGUAGES.map((l) => [l.value, l]));

export function labelForOriginalLanguage(value: string | null | undefined): string {
  if (value == null || value === "") return "Selecionar…";
  const hit = byValue.get(value);
  return hit?.label ?? value;
}

export function normalizeLanguageSearch(s: string): string {
  return s
    .toLowerCase()
    .normalize("NFD")
    .replace(/\p{M}/gu, "")
    .trim();
}

export function filterOriginalLanguages(
  query: string,
  list: OriginalLanguage[] = ORIGINAL_LANGUAGES,
): OriginalLanguage[] {
  const q = normalizeLanguageSearch(query);
  if (!q) return list;
  return list.filter((l) => {
    const hay = normalizeLanguageSearch(
      `${l.label} ${l.value} ${l.search}`,
    );
    return hay.includes(q);
  });
}
